import express from 'express';import cors from 'cors';import 'dotenv/config';import crypto from 'node:crypto';
import type{Driver,Lap,LocationPoint,Meeting,PitStop,PositionPoint,RaceControlEvent,Session,SessionResult,Stint,WeatherPoint}from'../src/types/openf1';import{avgLap,bestLap,mergeResults,pitDuration,slowestLap}from'../src/lib/calculations';import{analyzeDriverIssues}from'../src/lib/issueAnalyzer';
const app=express();app.use(cors());app.use(express.json({limit:'1mb'}));const BASE='https://api.openf1.org/v1';const cache=new Map<string,{exp:number,data:unknown}>();
async function openf1<T>(endpoint:string,ttl=10*60_000):Promise<T>{const key=BASE+endpoint,hit=cache.get(key);if(hit&&hit.exp>Date.now())return hit.data as T;const r=await fetch(key);if(!r.ok)throw new Error(`OpenF1 ${r.status}: ${await r.text()}`);const data=await r.json();cache.set(key,{exp:Date.now()+ttl,data});return data as T}
const safe=<T>(p:Promise<T>,fb:T)=>p.catch(()=>fb);async function bundle(sessionKey:string){const [drivers,results,laps,pits,stints,positions,rc,weather,overtakes,locations]=await Promise.all([safe(openf1<Driver[]>(`/drivers?session_key=${sessionKey}`),[]),safe(openf1<SessionResult[]>(`/session_result?session_key=${sessionKey}`),[]),safe(openf1<Lap[]>(`/laps?session_key=${sessionKey}`,30*60_000),[]),safe(openf1<PitStop[]>(`/pit?session_key=${sessionKey}`),[]),safe(openf1<Stint[]>(`/stints?session_key=${sessionKey}`),[]),safe(openf1<PositionPoint[]>(`/position?session_key=${sessionKey}`),[]),safe(openf1<RaceControlEvent[]>(`/race_control?session_key=${sessionKey}`),[]),safe(openf1<WeatherPoint[]>(`/weather?session_key=${sessionKey}`),[]),safe(openf1(`/overtakes?session_key=${sessionKey}`),[]),safe(openf1<LocationPoint[]>(`/location?session_key=${sessionKey}`,30*60_000),[])]);const enriched=mergeResults(drivers,results).map(d=>{const dl=laps.filter(l=>l.driver_number===d.driver_number);return{...d,bestLap:bestLap(dl),avgLap:avgLap(dl),pitCount:pits.filter(p=>p.driver_number===d.driver_number).length,issues:analyzeDriverIssues(d.driver_number,rc,d.result,pits,dl,positions)}});return{drivers,results,enriched,laps,pits,stints,positions,raceControl:rc,weather,overtakes,locations}}
app.get('/api/f1/meetings',async(req,res)=>{try{res.json(await openf1<Meeting[]>(`/meetings?year=${req.query.year??2025}`))}catch(e){res.status(502).json({error:String(e)})}});
app.get('/api/f1/sessions',async(req,res)=>{try{res.json(await openf1<Session[]>(`/sessions?meeting_key=${req.query.meetingKey}`))}catch(e){res.status(502).json({error:String(e)})}});
app.get('/api/f1/race/:sessionKey/summary',async(req,res)=>{try{const b=await bundle(req.params.sessionKey);const top3=b.enriched.filter(d=>d.result?.position).sort((a,b)=>(a.result?.position??99)-(b.result?.position??99)).slice(0,3);const loc=b.locations.filter((_,i)=>i%50===0).slice(0,2500);res.json({...b,top3,quick:{winner:top3[0]?.full_name??null,fastestLap:Math.min(...b.laps.map(l=>l.lap_duration??Infinity)),dnf:b.results.filter(r=>r.dnf).length,dsq:b.results.filter(r=>r.dsq).length,incidents:b.raceControl.length,mostPitStops:[...b.enriched].sort((a,b)=>b.pitCount-a.pitCount)[0]?.full_name??null,slowestPit:Math.max(0,...b.pits.map(p=>pitDuration(p)??0))},locations:loc})}catch(e){res.status(502).json({error:String(e)})}});
app.get('/api/f1/race/:sessionKey/driver/:driverNumber',async(req,res)=>{try{const b=await bundle(req.params.sessionKey),n=Number(req.params.driverNumber);res.json({driver:b.enriched.find(d=>d.driver_number===n),laps:b.laps.filter(l=>l.driver_number===n),pits:b.pits.filter(p=>p.driver_number===n),stints:b.stints.filter(s=>s.driver_number===n),positions:b.positions.filter(p=>p.driver_number===n),incidents:b.raceControl.filter(e=>e.driver_number===n),stats:{bestLap:bestLap(b.laps.filter(l=>l.driver_number===n)),avgLap:avgLap(b.laps.filter(l=>l.driver_number===n)),slowestLap:slowestLap(b.laps.filter(l=>l.driver_number===n))}})}catch(e){res.status(502).json({error:String(e)})}});
app.get('/api/f1/race/:sessionKey/compare',async(req,res)=>{try{const b=await bundle(req.params.sessionKey);const one=(n:number)=>{const laps=b.laps.filter(l=>l.driver_number===n),pits=b.pits.filter(p=>p.driver_number===n),d=b.enriched.find(x=>x.driver_number===n);return{driver:d,laps,pits,positions:b.positions.filter(p=>p.driver_number===n),stats:{bestLap:bestLap(laps),avgLap:avgLap(laps),pitCount:pits.length,issues:d?.issues.length??0}}};res.json({a:one(Number(req.query.driverA)),b:one(Number(req.query.driverB))})}catch(e){res.status(502).json({error:String(e)})}});
let token:{exp:number;value:string}|null=null;async function giga(messages:any[]){if(!process.env.GIGACHAT_AUTH_KEY)return 'ИИ-чат временно недоступен. Проверьте ключ GigaChat.';if(!token||token.exp<Date.now()){const r=await fetch('https://ngw.devices.sberbank.ru:9443/api/v2/oauth',{method:'POST',headers:{Authorization:`Basic ${process.env.GIGACHAT_AUTH_KEY}`,RqUID:crypto.randomUUID(),'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({scope:process.env.GIGACHAT_SCOPE??'GIGACHAT_API_PERS'})});const j:any=await r.json();token={value:j.access_token,exp:Date.now()+29*60_000}}const r=await fetch('https://gigachat.devices.sberbank.ru/api/v1/chat/completions',{method:'POST',headers:{Authorization:`Bearer ${token.value}`,'Content-Type':'application/json'},body:JSON.stringify({model:process.env.GIGACHAT_MODEL??'GigaChat',messages})});const j:any=await r.json();return j.choices?.[0]?.message?.content??'Не удалось получить ответ GigaChat.'}
app.post('/api/chat',async(req,res)=>{const sys='Ты — помощник по Формуле-1 внутри сайта аналитики гонок. Отвечай простым русским языком. Не выдумывай данные. Если данных нет, честно скажи. Формулируй аккуратно: возможный проблемный момент, Race Control отметил, по данным видно.';try{res.json({answer:await giga([{role:'system',content:sys},{role:'user',content:`Контекст гонки: ${JSON.stringify(req.body.context??{}).slice(0,8000)}`},...(req.body.messages??[])])})}catch(e){res.status(502).json({answer:'ИИ-чат временно недоступен. Проверьте ключ GigaChat.',error:String(e)})}});
app.listen(process.env.PORT??3001,()=>console.log('API on 3001'));
